name: Create Pull Request

on: [pull_request]

jobs:
  setup:
    steps: 
      - name: clone repository
        uses: actions/checkout@v2

      - name: restore lerna 
        uses: actions/cache@v2
        with: 
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: install dependencies
        run: yarn install --frozen-lockfile && yarn bootstrap

      - name: build packages
        run: yarn build

      - name: lint types and code
        run: yarn lint